name = "pastebin"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

kv_namespaces = [
    { binding = "rust_worker", id = "af1d182c17504fad9b3625f1599d99b9", preview_id = "df270984fc0147c3b3e73e1fa6e79328" }
]

[[d1_databases]]
binding = "DB"
database_name = "pastebin"
database_id = "e99c95f9-5a4e-4e21-b41c-de5528107ce7"

[build]
command = "cargo install -q worker-build && worker-build --release"

